### ISSUE TITLE
error message on startup if using fcitx5

### ISSUE THREAD

**Issue by tkkcc** [h-hg/fcitx.nvim#1]
Hi, I got following message on startup. 

![image](https://user-images.githubusercontent.com/17373509/145596009-4bb991ab-57e9-4c5f-8bfc-e791863cd181.png)

It's related to your `executable` function. If moving to the built in one, everything is find. 
```lua
local fcitx_cmd = ""
if vim.fn.executable("fcitx-remote") == 1 then
  fcitx_cmd = "fcitx-remote"
elseif vim.fn.executable("fcitx5-remote") == 1 then
  fcitx_cmd = "fcitx5-remote"
end
```

**Comment by h-hg** [comment]
Thanks. I have corrected my code. Everything goes well.

**Comment by tkkcc** [comment]
Thanks. It works.
